server:
  port: 8081  # Corregido 

spring:
  application:
    name: users-service # ¡Nombre clave para el Gateway!
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=UsuariosDb;encrypt=true;trustServerCertificate=true
    username: sa
    password: "Password_Fuerte_123!" # profe asegure el doker jsjs  que sea la correcta de tu Docker
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect

# ESTO FALTABA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true