spring.application.name=seguridades

server.port=8888
# SQL SERVER
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=security;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password= Admin123!
# jpa hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update